name: Go checks

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  source:
    uses: ./.github/workflows/checks.yml
  packaging:
    uses: ./.github/workflows/packaging.yml
